### ISSUE TITLE
Container-free installation instructions

### ISSUE THREAD

**Issue by bby-bishopclark** [grindsa/acme2certifier#100]
Our organization has experienced issues with containers going stale where those responsible aren't best equipped.

Do we have a container-free installation doc so we can light up a trivial (pair of?) trivial nginx hosts to accomplish the same install?

**Comment by grindsa** [comment]
Here are some instructions to install a2c on either [apache2](https://github.com/grindsa/acme2certifier/blob/master/docs/install_apache2_wsgi.md)  or [nginx](https://github.com/grindsa/acme2certifier/blob/master/docs/install_nginx_wsgi.md). Even if they have not been updated since quite some time, they should still be accurate. So its definitely worth to try but i will use this issue to review the instructions in the upcoming days...

Another option would be to get the installation instructions from the container files for [apache2](https://github.com/grindsa/acme2certifier/blob/master/examples/Docker/apache2/wsgi/Dockerfile)  or [nginx](https://github.com/grindsa/acme2certifier/blob/master/examples/Docker/nginx/wsgi/Dockerfile).

**Comment by bby-bishopclark** [comment]
This is pretty fantastic, I have to say.

If I can win some time to look into it, I'll try and enterprise it up a bit: packaging the main project, doing/finding some pip2rpm packages as well for the supply-chain concerns, and if I do I'll report back with my findings.

As it is, though, this has everything I need.  Thanks!!

**Comment by grindsa** [comment]
as promised i did update the documentation. There are also installation scripts availabe for:
- [a2c using apache2 on ubuntu 22.04](https://github.com/grindsa/acme2certifier/blob/master/examples/install_scripts/a2c-ubuntu22-apache2.sh)
- [a2c using nginx on ubuntu 22.04](https://github.com/grindsa/acme2certifier/blob/master/examples/install_scripts/a2c-ubuntu22-nginx.sh)
- [a2c using nginx on redhat/centos/alma 9](https://github.com/grindsa/acme2certifier/blob/master/examples/install_scripts/a2c-centos9-nginx.sh)

**Comment by bby-bishopclark** [comment]
I started on a proper package for the project, but since its dependencies peg it to only one actual major release of enterprise linux *that I haven't incorporated yet*, it's now stacked in-behind that.

A build is [here](https://download.copr.fedorainfracloud.org/results/bishopolis/misc/epel-9-x86_64/05072255-acme2certifier/acme2certifier-0.23.1-1.2.noarch.rpm) until COPR cleans it up, but it's not tested.  

1. `yum install epel-release`
1. `yum install` that URL
1. `chkconfig uwsgi on`
1. `service uwsgi start`

I need to put this down and get that new EL validated before picking this up in that context.  I can't run it until then with the supply-chain risks and with validation and consistency killed by `pip install`, but I'm looking forward to testing this out once I re-platform onto the right base.  Coupla months.  I'll have a vagrantfile by then too, as Vagrant testing is the next step for us.

**Comment by grindsa** [comment]
is there a chance to get the spec file you are using to create the RPM? I can integrate this in my build-pipline and build the rpm automatically with every new release.

**Comment by bby-bishopclark** [comment]
That's a fantastic idea!  The link above leads to the RPM *file*, but the dir it's in also includes a spec.  It looks a little cluttered, and it still needs a test, but COPR builds it well enough.  That spec is [here](https://download.copr.fedorainfracloud.org/results/bishopolis/misc/epel-9-x86_64/05072255-acme2certifier/acme2certifier.spec).

**Comment by grindsa** [comment]
[acme2certiifier 0.23.2](https://github.com/grindsa/acme2certifier/releases/tag/0.23.2) has been released today.  From now on RPM and DEB packages will created automatically and shipped along with the release.  The RPM package is based in your proposal with some smaller modification.  Testing was successful on my side so feel free to give it a try. 

Thank you for your contribution!

**Comment by bby-bishopclark** [comment]
Oh, this is fantastic news.  I'm still battling TPS reports and meatware outages to get my EL9 baseline, but I'll test that RPM with pleasure and review it with absolute joy.

Thank you SO much for carrying this the rest of the way, and I look forward to using it as soon as I can.
