### ISSUE TITLE
deb package overwrites configuration files

### ISSUE THREAD

**Issue by realslacker** [grindsa/acme2certifier#104]
Just attempted an upgrade to 0.25.1 and my config file got hosed. I was able to restore, but maybe it would be a good idea to make the default config file an example file so the production config isn't overwritten.

**Comment by grindsa** [comment]
Did you install the earlier version also via deb?

**Comment by realslacker** [comment]
Yes

**Comment by grindsa** [comment]
I changed the package in a way that `/var/www/acme2certifier/acme_srv.cfg` get flagged as config-file. So when upgrading the package you will get the below message:

```
(Reading database ... 145499 files and directories currently installed.)
Preparing to unpack .../acme2certifier_0.25.1-2_all.deb ...
Unpacking acme2certifier (0.25.1-2) over (0.25-1) ...
Setting up acme2certifier (0.25.1-2) ...

Configuration file '/var/www/acme2certifier/acme_srv/acme_srv.cfg'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** acme_srv.cfg (Y/I/N/O/D/Z) [default=N] ?
```

An [updated debian package](https://github.com/grindsa/acme2certifier/releases/download/0.25.1/acme2certifier_0.25.1-2_all.deb) is alreay available. Feel free to give it a try and let me know if it works for you.

PS: Please save your config file before testing :-)
