### ISSUE TITLE
Custom CA handler with no cert bundle

### ISSUE THREAD

**Issue by gdbarron** [grindsa/acme2certifier#106]
Thanks for a great project!  I'm building a custom ca handler and need to support only receiving a certificate from the CA.  I've tried to return None for cert_bundle, but that fails with a 500 on /finalize and seems to be required.  Is there any way to accomplish this?

**Comment by grindsa** [comment]
I think your observation is right. Any chance to get a debug log to be sure? I am wondering how are you passing the certificate to the client? Can you quickly describe your use-case? Maybe there is an easy workaround....

**Comment by grindsa** [comment]
any comment from your side? Or can i close the issue?

**Comment by gdbarron** [comment]
I'm so sorry for the delay, not sure how I missed the notifications.  The use case is the CA manages all the root/int certs and enrollment doesn't provide that data.  I have received a copy of those certs and will 'hardcode' them into the process and return the chain that way.  I have enabled debug logging but oddly not able to find where they live.  Could you let me know please?  Thanks!

**Comment by grindsa** [comment]
Ok. Let me summarize my understanding:

- Your CA does provide you End-Entity certificates only
- CA certificates (root and intermediate) certificates are stored locally
- You are planning to build the chain based on those certificates

If my understanding is correct I suggest leave the chain creation to the `enroll` method of your CA handler:

1. Specify the path to the CA certificates in acme_srv.cfg
2. Load the ca-certifiates from local file system
3. Enroll certificates from CA
4. Build the chain and "raw" certificate according to the [documentation](https://github.com/grindsa/acme2certifier/blob/master/docs/ca_handler.md)

You could potentically re-use parts of the [mswcce_ca_handler.py](https://github.com/grindsa/acme2certifier/blob/master/examples/ca_handler/mswcce_ca_handler.py) 

- [Load ca-variable "ca_bundle" from acme_srv.cfg](https://github.com/grindsa/acme2certifier/blob/master/examples/ca_handler/mswcce_ca_handler.py#L97)
- [Load ca-certificates](https://github.com/grindsa/acme2certifier/blob/master/examples/ca_handler/mswcce_ca_handler.py#L133)
- [create certificate chain](https://github.com/grindsa/acme2certifier/blob/master/examples/ca_handler/mswcce_ca_handler.py#L195)
- [create raw certificate](https://github.com/grindsa/acme2certifier/blob/master/examples/ca_handler/mswcce_ca_handler.py#L201)
	
Let me know if it works for you or if you need further help…

**Comment by gdbarron** [comment]
This is fantastic, thank you.  My only other question is where do the debug logs live if I turn them on?  I've seen the config for the format, but not where they live or how to change it.

**Comment by grindsa** [comment]
hi... do you still need help or can we close this issue?
