### ISSUE TITLE
acme server cannot obtain certificate on first try, it only works on the second try.

### ISSUE THREAD

**Issue by prosperazagy** [grindsa/acme2certifier#108]
hello grindsa!
we loved your acme2certifier project and wanted to implement it in our domain, with a ca using ADCS, but we ran into some problems which we were stuck on for some time on without much luck...
the thing is whenever the server processed a request, after the challenge requirements were met, when a certificate would usually be issued, instead we would get "order status is processing, Lets sleep and retry".
even after waiting the 600 seconds we didnt get the certificate.
if you ran the request again, it would work and give us the certificate.
we checked and the second request would only work if we waited over ~40 seconds from the first unsuccessful request.

after further investigation, the logs we recieved werent very different whether  it was successful or not.
when it failed retrieving the cert we didnt get errors, but when it did succeed we got 2 new lines which indicated that it retrieved the cert.

when we entered the ADCS server, we inspected the connection logs in the performance monitor.
there we found out that at the first request (the one that doesnt work) a connection is starting and doesnt close for 40 seconds with a non anonymus user for whatever reason, but when it does work after these 40 seconds the monitor shows that a connection starts and closes on the same second, which is very different.

if you have any more question to assist you to help us we will gladly give you what you need!
we really think that your project is the best for our usage so thats why we are so eager to solve this problem!
Thanks!

**Comment by grindsa** [comment]
Hi, i did not get any response into the email i did send to you. Does this problem still exist?

**Comment by grindsa** [comment]
closed due to inactivity....
