### ISSUE TITLE
limit issuable CNs of certificates

### ISSUE THREAD

**Issue by deep-42-thought** [grindsa/acme2certifier#11]
I'm using the openssl backend and would like to restrict the CN (and SANs) of the certificates that can be issued via acme to certain TLDs.
I can think of three approaches:
1. Configure a custom dns server which only answers queries for those TLDs
2. Filter the CN (and SANs) with a regex/whitelist
3. Sign the intermediate CA in a way, that restricts which CNs are allowed to be issued by the intermediate CA (some kind of "limited signature from the root CA")

What do you think, would be the best approach? (Is 3 even possible?)

**Comment by grindsa** [comment]
Option 1 does not really sound like a good approach. I am not sure if option 3 is even feasible when using openssl.

Option 2 seems to be the best way forward, but I would like to keep it out of acme2certifier. I think this is rather something the CA-handler should take care of as such kind of policing is a usual CA server task.

Easiest way would be to configure this black/white listing by using a "classical regex syntax" in `acme-srv.cfg`. Is this good enough?

**Comment by deep-42-thought** [comment]
yes, a regex in acme_srv.cfg would work. Thank you!

**Comment by deep-42-thought** [comment]
It seems possible to restrict the ca https://security.stackexchange.com/questions/31376/can-i-restrict-a-certification-authority-to-signing-certain-domains-only - however, support for this is not yet full, so the regex will definitely be of use to me :)

**Comment by grindsa** [comment]
I included SAN/CN black- and whitelisting into latest ´devel´ branch. Handler documentation has been updated. Give it a try.

**Comment by deep-42-thought** [comment]
I tested the whitelist and it seems to work. (I cannot say for sure, if the certificate failures for not-whitelisted FQDNs are because the regex or because I added `Name Constraints` to my root certificate in the meantime)
