### ISSUE TITLE
Challenge attempted with it turned off

### ISSUE THREAD

**Issue by gdbarron** [grindsa/acme2certifier#110]
I have my acme_srv.cfg setup with challenge_validation_disable set to True, but challenge is still attempted.  I am using apache installed on Ubuntu, not docker.  Please let me know any other details I can provide that might be helpful.

![image](https://github.com/grindsa/acme2certifier/assets/11862024/6579d405-9ef8-4283-a38c-663cdaad2810)

**Comment by grindsa** [comment]
Hi, I did not get a response so far. Do you need any more information?

**Comment by grindsa** [comment]
closed due to inactivity....
