### ISSUE TITLE
Support for Digicert ACME

### ISSUE THREAD

**Issue by wioxjk** [grindsa/acme2certifier#113]
I noticed that LetsEncrypt, ZeroSSL and BuyPass have official suppor in acme2certifier.
It would be nice if it supported Digicert aswell, since they have ACME support since a couple of years.

The Digicert ACME-API is supported be Certbot and basically all the major ACME-clients, so I guess that it would not be that hard to implement support for it in acme2certifier?

https://docs.digicert.com/en/certcentral/certificate-tools/certificate-lifecycle-automation-guides/use-a-third-party-acme-client-for-host-automations.html

**Comment by grindsa** [comment]
If Digicerts implementation follows RFC8555 it should work out of the box. So its rather the missing validation option preventing us to state interoperability.  Do you know if they have a free-of-charge staging environment we could use as part of our regression?
