### ISSUE TITLE
Error renewing certificate from LE

### ISSUE THREAD

**Issue by HenriWahl** [grindsa/acme2certifier#118]
Hi  @grindsa,

first thanks a lot for this great project which severely changed our whole certificate issuer process. We use it as an issuer for traefik against a local Windows Active Directory CA. Since last year when we introduced acme2certfier it served very well.

Now the first certificates are about to be renewed as they are valid for 13 months. This duration is a fixed one decided by the internal CA. But the same traefik instance which was able to request and get certificates from the CA via acme2certifier now fails to renew them. We see log messages like

```
traefik_1  | time="2023-08-24T15:28:40Z" level=debug msg="Building ACME client..." providerName=internal.acme
traefik_1  | time="2023-08-24T15:28:40Z" level=debug msg="https://acme.foobar.org" providerName=internal.acme
traefik_1  | time="2023-08-24T15:28:40Z" level=info msg="Error renewing certificate from LE : {Main:important.foobar.org SANs:[]}" ACME CA="https://acme.foobar.org" error="get directory at 'https://acme.foobar.org': Get \"https://acme.foobar.org\": EOF" providerName=internal.acme
```

We run the image grindsa/acme2certifier:0.29-nginx-wsgi from Dockerhub. Traefik is 2.10.4.
The config file we mount into the container is

```ini
[DEFAULT]

[Nonce]
nonce_check_disable: False

[CAhandler]
handler_file: examples/ca_handler/mscertsrv_ca_handler.py
host: https://acme.foobar.org
user: some_user
password: some_password
ca_bundle: volume/internal-rootca.pem
auth_method: ntlm
template: web_13_months

[DBhandler]

[Certificate]
revocation_reason_check_disable: False

[Challenge]
challenge_validation_disable: False

[Order]
tnauthlist_support: False
```

Is there something we configured wrong or is this expected behavior? Might it be fault by the CA or does acme2certifier simply not support renewal?

Thanks for any hint and best regards
Henri

**Comment by grindsa** [comment]
Hi @HenriWahl,

thank you for your feedback about our product.  Happy to hear that you like it.

Based on what you send its hard to drill down to a certain issue.

few questions:

- Do you see a chance to send me the logs from acme2certifier from the time of the failed enrollment?
- Can you check if enrollment of a new certificate works with the current release?
- Is there a chance to enable debugging to trigger the issue and send me the logs via email?

Debugging can be enabled by 

```
[DEFAULT]
debug: True
```
Logs are written to STDOUT.


In principle renewal should be supported. However we introduced some changes to improve [interoperability with traffik](https://github.com/grindsa/acme2certifier/commit/14e4cb0d78becc9c2a7c71c73a8ae542b6c2c759) and to support for Renewal information (ARI) extension. Could be that something got broken there and is now hurting you.

/G.

**Comment by HenriWahl** [comment]
@grindsa how strange, after I openend this ticket it worked and the failing certificates where renewed automatically...

Well, anyway I set `debug: True` now and will see what will be logged if this occurs annother time. I have no access to the old logs.

The enrollment of new certificates works like a charm as before now with the latest 0.29 version too.

I will let you know of any new findings.

**Comment by HenriWahl** [comment]
The next certificate which had to be renwed just worked flawlessly. So I guesst the issue had whatever cause I can't reproduce.
