### ISSUE TITLE
EAB signature verification issue

### ISSUE THREAD

**Issue by anttidantti** [grindsa/acme2certifier#129]
Hi, 

Thank you for your great work with a2m tool. I am trying to get my lab-env working and got stalled with following issue which I cannot figure out how to solve.
 
Running a2m 0.32 on RHEL 8
I am using Certbot as ACME client

Debug logs: 
[Wed Jan 24 16:14:34.254115 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Directory._config_load()
[Wed Jan 24 16:14:34.254839 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG load_config(/var/www/acme.calab.private/acme_srv/acme_srv.cfg:Directory)
[Wed Jan 24 16:14:34.259977 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Directory._config_load() ended
[Wed Jan 24 16:14:34.260523 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 INFO 192.168.64.3 /directory
[Wed Jan 24 16:14:34.261096 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Directory.directory_get()
[Wed Jan 24 16:14:34.261468 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG DBStore.dbversion_get()
[Wed Jan 24 16:14:34.265241 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG DBStore.dbversion_get() ended with 0.30
[Wed Jan 24 16:14:34.280946 2024] [wsgi:error] [pid 11231:tid 140716450588416] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Nonce.nonce_generate_and_add()
[Wed Jan 24 16:14:34.281486 2024] [wsgi:error] [pid 11231:tid 140716450588416] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Nonce.nonce__new()
[Wed Jan 24 16:14:34.282199 2024] [wsgi:error] [pid 11231:tid 140716450588416] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG got nonce: 3aef43f77bf64324bc9fdb9fec6a5e85
[Wed Jan 24 16:14:34.282585 2024] [wsgi:error] [pid 11231:tid 140716450588416] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG DBStore.nonce_add(3aef43f77bf64324bc9fdb9fec6a5e85)
[Wed Jan 24 16:14:34.299978 2024] [wsgi:error] [pid 11231:tid 140716450588416] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG DBStore.nonce_add() ended
[Wed Jan 24 16:14:34.300460 2024] [wsgi:error] [pid 11231:tid 140716450588416] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Nonce.generate_and_add() ended with:3aef43f77bf64324bc9fdb9fec6a5e85
[Wed Jan 24 16:14:34.332320 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG _config_load()
[Wed Jan 24 16:14:34.337736 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG error_dict_get()
[Wed Jan 24 16:14:34.338338 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Account._config_load()
[Wed Jan 24 16:14:34.343297 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Account._config.load(): loading eab_handler
[Wed Jan 24 16:14:34.343741 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Helper.eab_handler_load()
[Wed Jan 24 16:14:34.348143 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Account._config_load() ended
[Wed Jan 24 16:14:34.348766 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Account.new()
[Wed Jan 24 16:14:34.349325 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Message.check()
[Wed Jan 24 16:14:34.349705 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG decode_message()
[Wed Jan 24 16:14:34.350930 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Message._check()
[Wed Jan 24 16:14:34.351481 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Nonce.check_nonce()
[Wed Jan 24 16:14:34.351974 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Nonce.nonce._check_and_delete(3aef43f77bf64324bc9fdb9fec6a5e85)
[Wed Jan 24 16:14:34.352461 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG DBStore.nonce_check(3aef43f77bf64324bc9fdb9fec6a5e85)
[Wed Jan 24 16:14:34.356261 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG DBStore.nonce_check() ended
[Wed Jan 24 16:14:34.356704 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG DBStore.nonce_delete(3aef43f77bf64324bc9fdb9fec6a5e85)
[Wed Jan 24 16:14:34.365175 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG DBStore.nonce_delete() ended
[Wed Jan 24 16:14:34.365662 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Nonce._check_and_delete() ended with:200
[Wed Jan 24 16:14:34.366066 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Nonce.check_nonce() ended with:200
[Wed Jan 24 16:14:34.366593 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Message._name_get()
[Wed Jan 24 16:14:34.366983 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Message._name_get() returns: None
[Wed Jan 24 16:14:34.372279 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG error_dict_get()
[Wed Jan 24 16:14:34.377238 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Signature.check(None)
[Wed Jan 24 16:14:34.377656 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG check signature against key includedn in jwk
[Wed Jan 24 16:14:34.378077 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG signature_check(False)
[Wed Jan 24 16:14:34.381632 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Signature.check() ended with: True:None
[Wed Jan 24 16:14:34.382146 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Message._check() ended with: 200
[Wed Jan 24 16:14:34.382559 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Message.check() ended with:200
[Wed Jan 24 16:14:34.383138 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Account._new()
[Wed Jan 24 16:14:34.383525 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG _eab_check()
[Wed Jan 24 16:14:34.383867 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG _eab_jwk_compare()
[Wed Jan 24 16:14:34.384404 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG b64decode_pad()
[Wed Jan 24 16:14:34.384972 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG _eab_jwk_compare() ended with: True
[Wed Jan 24 16:14:34.385316 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG _eab_check()
[Wed Jan 24 16:14:34.385696 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG _eab_kid_get()
[Wed Jan 24 16:14:34.386016 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG b64decode_pad()
[Wed Jan 24 16:14:34.386788 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG _eab_kid_get() ended with: fde4147a-672c-4625-acee-c1eb69523711
[Wed Jan 24 16:14:34.387188 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG EABhandler._config_load()
[Wed Jan 24 16:14:34.387611 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG load_config(/var/www/acme.calab.private/acme_srv/acme_srv.cfg:EABhandler)
[Wed Jan 24 16:14:34.392500 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG EABhandler._config_load() ended
[Wed Jan 24 16:14:34.393023 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG EABhandler.mac_key_get(fde4147a-672c-4625-acee-c1eb69523711)
[Wed Jan 24 16:14:34.394255 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG EABhandler.mac_key_get() ended with: True
[Wed Jan 24 16:14:34.394661 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Account._eab_signature_verify()
[Wed Jan 24 16:14:34.399425 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG error_dict_get()
[Wed Jan 24 16:14:34.404187 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Signature.eab_check()
[Wed Jan 24 16:14:34.404612 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG signature_check(True)
[Wed Jan 24 16:14:34.405391 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Account._eab_signature_verify() ended with: False
[Wed Jan 24 16:14:34.405787 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 ERROR Account._eab_check() returned error: None
[Wed Jan 24 16:14:34.406245 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG _eab_check() ended with: 403
[Wed Jan 24 16:14:34.406628 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Account._eab_check() ended with:403
[Wed Jan 24 16:14:34.406978 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Account._new() ended with: 403
[Wed Jan 24 16:14:34.407524 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Message.prepare_response()
[Wed Jan 24 16:14:34.407907 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Error.enrich_error()
[Wed Jan 24 16:14:34.408245 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Error.acme_errormessage(urn:ietf:params:acme:error:unauthorized)
[Wed Jan 24 16:14:34.408661 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Nonce.nonce_generate_and_add()
[Wed Jan 24 16:14:34.408999 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Nonce.nonce__new()
[Wed Jan 24 16:14:34.409494 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG got nonce: dd3c751db969422281a56a6ee0d43cdc
[Wed Jan 24 16:14:34.409922 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG DBStore.nonce_add(dd3c751db969422281a56a6ee0d43cdc)
[Wed Jan 24 16:14:34.418659 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG DBStore.nonce_add() ended
[Wed Jan 24 16:14:34.419080 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Nonce.generate_and_add() ended with:dd3c751db969422281a56a6ee0d43cdc
[Wed Jan 24 16:14:34.419728 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 DEBUG Account.new() returns: {"code": 403, "header": {"Replay-Nonce": "dd3c751db969422281a56a6ee0d43cdc"}, "data": {"status": 403, "type": "urn:ietf:params:acme:error:unauthorized", "detail": "eab signature verification failed"}}
[Wed Jan 24 16:14:34.420465 2024] [wsgi:error] [pid 11231:tid 140716265166592] [remote 192.168.64.3:60144] 2024-01-24 16:14:34 INFO 192.168.64.3 /acme/newaccount {'code': 403, 'header': {'Replay-Nonce': '- modified -'}, 'data': {'status': 403, 'type': 'urn:ietf:params:acme:error:unauthorized', 'detail': 'eab signature verification failed'}}

**Comment by grindsa** [comment]
Hi, which eab-handler are you using for testing? Do you mind sharing your key-file? I know that this is a bid tricky, but it would help to troubleshoot your issue. You can also share via email to grindelsack <at> gmail.com

**Comment by anttidantti** [comment]
Hi, 
The one found in examples/json_handler.py

I don't mind sharing the key as this is just for testing / lab purposes. I'll send it to you in an email (or contents of it).

**Comment by grindsa** [comment]
Thank you for providing test-key and mac strange thing is that it works on my side.

Which certbot version are you using? Further, can you please share the `[EABhandler]` section of acme_srv.cfg (just to exclude a configuratio issue).

Thx
GrindSa

**Comment by anttidantti** [comment]
Hi, 

certbot 2.6.0 from RHEL9 standard repository. 

[EABhandler]
eab_handler_file: /var/www/acme.calab.private/acme_srv/json_handler.py
key_file: /var/www/acme.calab.private/acme_srv/key_file.json

For some reason I couldn’t get relative paths to work, so full path provided in the config. 


//Antti

**Comment by grindsa** [comment]
I was finally able to replicate the issue. Problems lies outside of acme2certifier but in the python3-jwcrypto packages shipped along with Redhat8.  This version 0.5.0 seems to contain a bug which prevents a json-based jwk to load and as a result both signature verification and eab will fail.

I created attached backport from the package used in Redhat9. [python3-jwcrypto-0.8-4.el8.noarch.rpm.zip](https://github.com/grindsa/acme2certifier/files/14076840/python3-jwcrypto-0.8-4.el8.noarch.rpm.zip) as the problem does not exists there.

After upgrading the package with `rpm -Uvh ...` and restarting the acme2certifier service eab seems to work.

Please try on your side and let me know if it works for you as well...

**Comment by anttidantti** [comment]
Hi, 

Thank you for your great help, yes I can confirm the issue resolved and I am able to continue with the experiment further. 

Keep up the good work, really appreciate. 

Closing this issue.

**Comment by anttidantti** [comment]
Closed resolved.
