### ISSUE TITLE
a2c dns-o1 issue

### ISSUE THREAD

**Issue by anttidantti** [grindsa/acme2certifier#133]
Hi, 

I've run into an issue that I cannot figure out myself when trying to get dns-01 challenge based validation to work with a2c. 

a2c v 0.32.0 (haven't yet have time to upgrade to 0.33.1). 

Configuration: 
DNS Bind 32:9.16.23-14.el9_3 on RHEL9 

Configured tested domains for autoupdate by Certbot client. 
Certbot 2.6.0 on RHEL 9 having RFC2136 authenticator plugin installed for dns-01 validation

a2c running on RHEL 8.

Issue is that for some reason a2c cannot get the validation challenge from the DNS server. 

Here's sample certbot run trying it to request certificate for host that does not offer http-challenge option. 

sudo certbot certonly -v -c bot3/certbot.ini -d logger.calab.private -d ctlog.calab.private
Saving debug log to bot3/logs/letsencrypt.log
Plugins selected: Authenticator dns-rfc2136, Installer None
Requesting a certificate for logger.calab.private and ctlog.calab.private
Performing the following challenges:
dns-01 challenge for logger.calab.private
dns-01 challenge for ctlog.calab.private
Waiting 60 seconds for DNS changes to propagate

Dig from the acme server command line to verify that the challenge is in fact in the DNS
dig _acme-challenge.logger.calab.private -t TXT

; <<>> DiG 9.11.36-RedHat-9.11.36-11.el8_9 <<>> _acme-challenge.logger.calab.private -t TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16441
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 8ed9b8f3971c1e710100000065ca2a1ce85db61adb8bceb1 (good)
;; QUESTION SECTION:
;_acme-challenge.logger.calab.private. IN TXT

;; ANSWER SECTION:
_acme-challenge.logger.calab.private. 120 IN TXT "2vmS25hVk2rCqV6nHoJxXmU6MV6slDMO8B7qu1HRsds"

;; Query time: 1 msec
;; SERVER: 192.168.64.100#53(192.168.64.100)
;; WHEN: Mon Feb 12 16:24:27 EET 2024
;; MSG SIZE  rcvd: 149

└─$ dig _acme-challenge.ctlog.calab.private -t TXT

; <<>> DiG 9.11.36-RedHat-9.11.36-11.el8_9 <<>> _acme-challenge.ctlog.calab.private -t TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37759
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; COOKIE: 780bff3a2b1db57b0100000065ca2a453ba310a9ebd52da1 (good)
;; QUESTION SECTION:
;_acme-challenge.ctlog.calab.private. IN	TXT

;; ANSWER SECTION:
_acme-challenge.ctlog.calab.private. 120 IN TXT	"k8taNJFD6iQpTFF2swexCOMJAVsO97DXtCWWhsUgzZ4"

;; Query time: 1 msec
;; SERVER: 192.168.64.100#53(192.168.64.100)
;; WHEN: Mon Feb 12 16:25:08 EET 2024
;; MSG SIZE  rcvd: 148

Error in the a2c log for the above challenges

[Mon Feb 12 16:24:44.901927 2024] [wsgi:error] [pid 1525:tid 139695826904832] 2024-02-12 16:24:44 DEBUG response_got: [] response_expected: b'2vmS25hVk2rCqV6nHoJxXmU6MV6slDMO8B7qu1HRsds'

[Mon Feb 12 16:24:45.270650 2024] [wsgi:error] [pid 1525:tid 139695826904832] 2024-02-12 16:24:45 DEBUG response_got: [] response_expected: b'k8taNJFD6iQpTFF2swexCOMJAVsO97DXtCWWhsUgzZ4'

Based on the dig-verification to me it looks as if all OK, but it seems that the query made by a2c does not get the request data. I've tried with explicitly defining DNS server in the acme_srv.cfg and without with same result. 

Further here's the entries in the DNS server log for challenge entry and clean-up after a2c responds to the certbot with fail. 

Feb 12 16:23:45 identity named[928]: client @0xffff98034be8 192.168.64.30#50412/key calab-bot: updating zone 'calab.private/IN': adding an RR at '_acme-challenge.logger.calab.private' TXT "2vmS25hVk2rCqV6nHoJxXmU6MV6slDMO8B7qu1HRsds"
Feb 12 16:23:45 identity named[928]: client @0xffff98034be8 192.168.64.30#50448/key calab-bot: updating zone 'calab.private/IN': adding an RR at '_acme-challenge.ctlog.calab.private' TXT "k8taNJFD6iQpTFF2swexCOMJAVsO97DXtCWWhsUgzZ4"
Feb 12 16:26:25 identity named[928]: client @0xffff9406ef18 192.168.64.30#51778/key calab-bot: updating zone 'calab.private/IN': deleting an RR at _acme-challenge.logger.calab.private TXT
Feb 12 16:26:25 identity named[928]: client @0xffff9406ef18 192.168.64.30#51796/key calab-bot: updating zone 'calab.private/IN': deleting an RR at _acme-challenge.ctlog.calab.private TXT

Any ideas where to look? I cannot figure this out myself. 

Thanks in advance

**Comment by grindsa** [comment]
I am sorry i just noticed that my update did not went through...

Based on the logs i assume that the response from the DNS server does not contain the needed TXT records even if the dig response clearly proves the records to be there...

Are you able to trace the dns-traffic between a2c and provide a pcap?

**Comment by anttidantti** [comment]
[pcap.tar.gz](https://github.com/grindsa/acme2certifier/files/14302234/pcap.tar.gz)
Here is a try, not sure if I could get what you wanted. From both ends, dns and acme servers.

**Comment by grindsa** [comment]
Sorry for not being precisely enough. Can you please trigger a certificate enrollment, collect the logs from a2c and capture the dns-traffic between a2c-server and your DNS?

I would like to see if a2c is querying the TXT records correctly. DNS-01 challenge validation works fine in our regression, so I suspect a timing issue or something similar.

**Comment by anttidantti** [comment]
Here's new try. 
  The traffic captured in the dns.pcap from the dns server during 
  sudo certbot certonly -v -c bot3/certbot.ini -d logger.calab.private -d ctlog.calab.private
Saving debug log to /home/batman/bot3/logs/letsencrypt.log
Plugins selected: Authenticator dns-rfc2136, Installer None
Requesting a certificate for logger.calab.private and ctlog.calab.private
Performing the following challenges:
dns-01 challenge for logger.calab.private
dns-01 challenge for ctlog.calab.private
Waiting 60 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
All authorizations were not finalized by the CA.

stripped log from acme-server (error log)

also capture from the acme server side (acme.pcap), not sure if its for any help though. 

capture command used on both servers: 
sudo tcpdump -i any -w dns.pcap (or acme.pcap)

[a2c.tar.gz](https://github.com/grindsa/acme2certifier/files/14308272/a2c.tar.gz)

If I did something incorrectly or something I could do better, please advice.

**Comment by grindsa** [comment]
```
[Fri Feb 16 10:00:29.697427 2024] [wsgi:error] [pid 1506:tid 140267222193920] 2024-02-16 10:00:29 DEBUG txt_get(_acme-challenge.logger.calab.private: None)
[Fri Feb 16 10:00:29.697874 2024] [wsgi:error] [pid 1506:tid 140267222193920] 2024-02-16 10:00:29 ERROR txt_get() error: module 'dns.resolver' has no attribute 'resolve'
[Fri Feb 16 10:00:29.698250 2024] [wsgi:error] [pid 1506:tid 140267222193920] 2024-02-16 10:00:29 DEBUG txt_get() ended with: []
[Fri Feb 16 10:00:29.698707 2024] [wsgi:error] [pid 1506:tid 140267222193920] 2024-02-16 10:00:29 DEBUG response_got: [] response_expected: b'0nvlEuRWtEkq7DHldELbeu6pJK8EF2L-kSTTNGRw8Fs'
[Fri Feb 16 10:00:29.699066 2024] [wsgi:error] [pid 1506:tid 140267222193920] 2024-02-16 10:00:29 DEBUG validation not successful
```

indicates a problem with the DNS python module. Which version are you using? Can you send me the output of `pip3 show dnspython`?

**Comment by anttidantti** [comment]
Name: dnspython
Version: 1.15.0
Summary: DNS toolkit
Home-page: http://www.dnspython.org
Author: Bob Halley
Author-email: halley@dnspython.org
License: BSD-like
Location: /usr/lib/python3.6/site-packages
Requires:

**Comment by anttidantti** [comment]
Hi, upgraded dnspython and it started to work. Thanks again for your superb help. One hurdle overcome in my experiment...

Really appreciate your good work.

**Comment by anttidantti** [comment]
Closing this issue.

**Comment by grindsa** [comment]
Just fyi...

I created a backport of the [python3-dns package](https://github.com/grindsa/sbom/raw/main/rpm-repo/RPMs/python3-dns-2.1.0-6.el8.noarch.rpm) used in Redhat9 to eliminate to run pip to update the package.

Further to avoid that you are running into the next problem: I noticed another Issues related tls-alpn-01 challenge validation caused by the very old cryptography package coming along with RH8. Again, you need a [backport from RH9](https://github.com/grindsa/sbom/raw/main/rpm-repo/RPMs/python3-cryptography-36.0.1-4.el8.x86_64.rpm) to address this.
