### ISSUE TITLE
acme_srv_housekeeping dbversion ist set back to 0.23.1 after container restart

### ISSUE THREAD

**Issue by rafaelorafaelo** [grindsa/acme2certifier#135]
Hi,
I have always warning in my container log using the Docker image acme2certifier:nginx-django about a database version mismatch 0.23.1, where it should be 0.33. My observations is: when I run django_update.py from inside the container, acme_srv_housekeeping dbversion is set from 0.23.1 to 0.33. When I restart the container, this value is set back to 0.23.1.
Regards,
Ralf

**Comment by grindsa** [comment]
Hi, 

Thx for reporting this. Seems I forgot to update the fixture.xml for a little while. Fix is included in [v0.33.2](https://github.com/grindsa/acme2certifier/releases/tag/0.33.2). Feel free to test and let me know it solves your problem.

BR G.

**Comment by rafaelorafaelo** [comment]
Works, great. Thanks.
