### ISSUE TITLE
ARM images

### ISSUE THREAD

**Issue by tomaszkiewicz** [grindsa/acme2certifier#138]
Hi, is it possible you publish ARM64 images as well, please?

**Comment by grindsa** [comment]
Give me a couple of days to look into it.

**Comment by grindsa** [comment]
Can you please describe the environment you want to deploy on? What is your preferred stack apache2/nginx wsgi/Django? Which ca-Handler are you planning to use? 

Creating an image should not be a big issue. Problem is rather to find an environment for testing. Hence my questions...

/G.

**Comment by tomaszkiewicz** [comment]
If you release ARM version I can quickly test it on my cluster :)

**Comment by grindsa** [comment]
Hi,

try `docker pull grindsa/acme2certifier:arm64`

/G.

**Comment by tomaszkiewicz** [comment]
It's working, I mean:

- I created a container based on the one specified above
- added my own openssl_ca_handler.py to it
- deployed to ARM-based node
- tested with acme.sh with register account operation (as I don't setup with all certs on that cluster yet)

So I think you can safely integrate that with base image to have a multi-arch container :)

**Comment by grindsa** [comment]
thank you for your confirmation. I am not really familar woth multi-arch images. Thus,  let me play a few days with it and adapt the  workflows for image creation...

**Comment by grindsa** [comment]
The test-pipeline has been created and the workflows to publish and test the images have been adapted. So far all looks good. Feel free to use the official arm64 images from now on...

/G.

**Comment by tomaszkiewicz** [comment]
Seems to work perfectly, thanks a lot! :)
