### ISSUE TITLE
allowed_domainlist and the mscertsrv_ca_handler.py

### ISSUE THREAD

**Issue by gbit-is** [grindsa/acme2certifier#160]
I wanted the allowed_domainlist functionality avaivable in some other handlers for the mscertsrv handler, so I implemented it by copy pasting the functionality from the "acme_ca_handler.py" to it.

Is this something that you would want ?
If so, it would be no issue to do a pull/merge request but if this is of no interest, then no need to waste time on that :)

**Comment by grindsa** [comment]
Hi, 

PRs are always welcome... Please raise against devel branch...

/G.

**Comment by gbit-is** [comment]
Cool, I have done so :)
