### ISSUE TITLE
configure external log for acme_srv

### ISSUE THREAD

**Issue by raschidb** [grindsa/acme2certifier#162]
Hello,
Is there a way to configure the logger from acme_srv file.
Currently i have installed on a redhat OS from rpm package.

The program run as a service. I could configure rsyslog to send the log outside /var/log/message but the program source is "bash" ...
Or may i have missed something in the configuration ?

Thank you
Rachid.

**Comment by grindsa** [comment]
Hi,

I think there are multiple ways to achieve what you want. I usually do it in two steps:

1. modify `acme_srv.cfg`, insert a specific log_format and restart acme2certiifer:
```
[Helper]
log_format: 'acme2certifier - %(message)s'
````

2. modify your `rsyslog.conf`, add something like the below and restart rsyslog

```
:msg, contains, "acme2certifier" -/var/log/a2c.log
```

After this you should find a `/var/log/a2c.log` containing the logs from acme2certifier...

**Comment by raschidb** [comment]
Hi,
Thank you it didn't goes as i wanted, and by this way i didn't get uWSGI logs (outside python)
Finally i get a better solution 
Modify the service file :
/usr/lib/systemd/system/acme2certifier.service

and add those options :
StandardOutput=append:/var/log/a2c.log
StandardError=append:/var/log/a2c.log


Thank you.
Rachid

**Comment by okorsky** [comment]
Hi @raschidb 

Could you please share more info on this? what's the whole content of the service file /usr/lib/systemd/system/acme2certifier.service?

I'm running acme2certifier with wsgi and apache2.

Thank you!

**Comment by raschidb** [comment]
Hi okorsky,

Sure :)
please find the service file content below : 
It runs on RedHat 9 anf Nginx 

 ----
[Unit]
Description=uWSGI instance to serve acme2certifier

[Service]
RuntimeDirectory=uwsgi
ExecStart=/usr/bin/bash -c 'cd /opt/acme2certifier; uwsgi --ini acme2certifier.ini'
StandardOutput=append:/VAR/acme/logs/acme_app.log
StandardError=append:/VAR/acme/logs/acme_app.log
Restart=always
Type=notify
NotifyAccess=all
WorkingDirectory=/opt
User=acme

[Install]
WantedBy=multi-user.target
----

Rachid

**Comment by okorsky** [comment]
Thank you so much, Rachid :)

Much appreciated!
