### ISSUE TITLE
Support for multi profile with EJBCA

### ISSUE THREAD

**Issue by florian-leparoux-phenom** [grindsa/acme2certifier#167]
Hello, 

I search on the project about some documentation on how to have multi profile for ejbca. 
I haven't found anything about it. So I assume it's not yet possible.

I found something about potential support on demand, so I try here.

Would it be possible to support multiple profile.
One of my use case is to generate certificate from k8s using cert-manager and issuer to perform client/server authentication.

My current ejbca setup has 2 profiles to handle this.

Do you know if it's possible ? 
Anything I can do to help on it ?

Thank you for the great job!

**Comment by grindsa** [comment]
Hi,

you are right. As of today, the ejbca handler does support a single profile only.  Extending the handler is not a big effort, so far i did not do it as nobody was asking for it and I am not using EJBCA. I even see two options:

1 [via eab_profiling](https://github.com/grindsa/acme2certifier/blob/master/docs/eab_profiling.md) - you would have to external account binding and can configure different profiles per keyid used during account registration
2 [via headerinfo feature](https://github.com/grindsa/acme2certifier/blob/master/docs/header_info.md) in which an acme-client can specify the profile-name as part of the enrollment

Not sure if option 2 is possible when using cert-manager.  

So if you are good with option 1 let me know and i will give it a try during the upcoming days.  If you want to help send me the xml exports of your certificate profiles; this would accelerate few things as I am not an ejbca expert.

**Comment by florian-leparoux-phenom** [comment]
Hi, 

Option 1 sounds good to me. 
I attached the 2 profiles I have for the client/server. Let me know if this answer your needs.

[Archive.zip](https://github.com/user-attachments/files/15925260/Archive.zip)

**Comment by grindsa** [comment]
Hi,

I updated the [ejbca-handler](https://github.com/grindsa/acme2certifier/blob/devel/examples/ca_handler/ejbca_ca_handler.py#L275) in [devel-branch](https://github.com/grindsa/acme2certifier/tree/devel) with [eab-profiling feature](https://github.com/grindsa/acme2certifier/blob/devel/docs/ejbca.md#eab-profiling). Tests are looking good so feel free to give it a try. 

A docker image using the wsgi handler is available on dockerhub via `docker pull grindsa/acme2certifier:devel`.

You can also update your installation manually by replacing `acme_srv/helper.py` and `examples/ca_handler/ejbca_ca_handler.py` with the version stored in [devel](https://github.com/grindsa/acme2certifier/tree/devel).

Feedback is welcome...

**Comment by grindsa** [comment]
Feature made it into [v0.35](https://github.com/grindsa/acme2certifier/releases/tag/0.35). Thus, closing this issue. In case you have comments feel free to reopen...
