### ISSUE TITLE
wildcard domain validation for DNS challange fails

### ISSUE THREAD

**Issue by flosch-dev** [grindsa/acme2certifier#19]
when requesting certificates via DNS-01 challange and using domain wildcard like *.example.com, acme2certifier tries to request TXT records with * 
following client request produced specific DNS requests: 
`acme.sh --server http://acme2certifier_srv_1  --renew -d *.example.com --dns --yes-I-know-dns-manual-mode-enough-go-ahead-please --output-insecure --force`
DNS queries:
`TXT? _acme-challenge.*.example.com. (47)`
`NXDomain 0/1/0 (103)`
`TXT? _acme-challenge.*.example.com. (47)`
`NXDomain 0/1/0 (103)`
`TXT? _acme-challenge.*.example.com. (47)`
`NXDomain 0/1/0 (103)`
`TXT? _acme-challenge.*.example.com. (47)`
`NXDomain 0/1/0 (103)`

**Comment by grindsa** [comment]
fixed in 142232d. please give it a try and let me know it it works...

**Comment by flosch-dev** [comment]
Great, it's working. Tested with acme.sh (v2.8.6)
