### ISSUE TITLE
SAN limit

### ISSUE THREAD

**Issue by judzk** [grindsa/acme2certifier#195]
Hi, we are using acme2certifier with ours haproxy RP. But we facing a issue
We want to issue only one certificate, with several alternate domain name. It's work great for 20 domains, but not for 21.

We got a error : 
```
unexpected error occurred:
AttributeError: can't set attribute
```

certbot 2.1.0 on debian 12 for Haproxy
Latest acme2certifier on a debian 12

**Comment by grindsa** [comment]
I am not aware of any limitation related to the number of SANs. Could be that cerbot runs into a timeout error.

Can you please share `/var/log/letsencrypt/letsencrypt.log`? Further i would need the log from acme2certifier from the failed enrollment with `debug: True` enabled in acme_srv.cfg. 

Feel free to share via email to grindelsack@gmail.com

/G.

**Comment by grindsa** [comment]
Sorry for my former comment which was misleading. What you observe is not a bug but a feature.

acme2certifier is limiting the number of SANs for security reasons to 20.

This limit can be changed in `acme_srv.cfg`
```cfg
[Order]
identifier_limit: <new value>
``` 
Check the [documentation](https://github.com/grindsa/acme2certifier/blob/master/docs/acme_srv.md) for further information

Please change the value and let me know if this works for you.

/G.

**Comment by judzk** [comment]
Hi, it works but now i have a time out, i will try the different option like `retry_after_timeout`,
thank you for your very quick answer

**Comment by grindsa** [comment]
Which ca_handler are you using? 

If fear that the `retry_after_timeout` will be of limited help and suggest playing with the enrollment timeout parameter instead

```cfg
[Certificate]
enrollment_timeout: 30
```

**Comment by judzk** [comment]
We use Sectigo. I managed to get it working with 
`--issuance-timeout 600` on certbot side
