### ISSUE TITLE
custom DNS server in acme_srv.cfg

### ISSUE THREAD

**Issue by flosch-dev** [grindsa/acme2certifier#20]
This is improvement request allowing to add (optional) DNS server for challange validation.

**Comment by grindsa** [comment]
Nice idea. I pushed a094a14 and 8d4d7fc to [devel](/grindsa/acme2certifier/tree/devel).  Give it a try and let me know if it works.

**Comment by flosch-dev** [comment]
great, works perfect. 
I've test with single DNS with single srv entry as well as 2 entries where 1st was unreachable.
