### ISSUE TITLE
Support for long-term polling for certificates

### ISSUE THREAD

**Issue by pfisterer** [grindsa/acme2certifier#3]
Dear @grindsa,
Thanks a million for uploading `acme2certifier` to Github. I'm currently evaluating whether I can use it for my - quite special - use case. 

I had a look at <https://github.com/grindsa/acme2certifier/blob/master/docs/ca_handler.md> and I'm not sure whether I can simply implement `enroll`. As far as I've understood your code, `enroll` basically gets a CSR and immediately returns the certificate.

My setup is as follows:
- I have access to a SOAP-based web service (which I cannot change) 
- This service issues certificates for a certain subdomain

I've implemented a SOAP client according to the spec of the server-side that can request certificates as follows:
- Send the request (i.e., the CSR) to the SOAP server
- Poll the SOAP server until the certificate is available

I assume that I cannot block `enroll` for some (probably quite long time) until the certificate is available. Is this correct? Is there any way to change the current behaviour such that enroll would invoke a callback once the certificate is available?

Best,
Dennis

**Comment by grindsa** [comment]
Hi,

I had a callback function from  ```enroll``` in the backlog for quite some time. So lets start with it. Current plan is that

- ```enroll``` returns a kind of “identifier” if a csr goes into “pending” state which will be stored in the database
- The ca_handler will be extended by a ```poll``` method which gets the identifier as input. Right now I am thinking to call the poll method via an external script which gets started via cron (just to see if the concept works).

Would this work for you? 

My CA server has also the option to send a trigger to acme2certifier after certificate issuance which then could call the ```poll``` method to download the certificate. Would this also be an option for you?

Will your acme-client be able to handle log-term polling situations? I am asking as I was checking [acme.sh](https://github.com/acmesh-official/acme.sh) and [certbot](https://github.com/certbot/certbot). Both have polling capabilities but just for very short timeframe. And once this is expired they will abort with a timeout error.

Best
G.

**Comment by pfisterer** [comment]
Hi @grindsa,
Great, Thank you!

Actually, my setup is very similar to yours, then. My SOAP client would poll the CA's SOAP service regularly to check whether the requested certificate is available. If this is the case, I could invoke trigger polling.

Just out of curiosity: how would your cron-job setup look like? How would you invoke the actual implementation of `poll`? 

Reg. the  acme-client: I'm using https://cert-manager.io/ with Kubernetes and assume that it will continuously poll for certificates. In a first step, I will implement the SOAP client side and wait for poll support to be available.

Best regards,
Dennis

**Comment by grindsa** [comment]
Hi Dennis,

I pushed the first set of changes to devel branch.  There is not much documentation yet thus let me try to explain here.

I assume that if a CSR gets into “pending” state the CA server sends information as part of the enrollment response which can used to lookup the status of the request.  In my example it would be a REST-URL I can poll.  This information must be returned by your ca.handler.enroll() method (variable ```poll_identifier```) and will be stored in the database along with the CSR (table ```certificate``` field ```poll_identifier```).

There is a script ```cert_poll.py``` in the tools directory which can be called via cron. It scans the ```orders``` table for orders in status ```processing``` (4) and passes the ```poll_identifier``` along with other information via the ```certificate.poll()``` to a ```poll``` method which must be part of your CA handler.  

The ```ca_handler.poll()``` method checks the status of the CSR on CA server and downloads the certificate (if available). It further builds the cert-chain and returns the below information back to ```certificate.poll()```  which will update the database.  
- An error-message (if there is any)
- Certificate chain in pem-format
- The raw cert (needed to lookup in case of revocation)
- An updated poll_identifier 
- An indication (True/False) if the CSR got rejected

In parallel the order-status will be set to ```valid```. So, if an acme-client polls the order-resource a URL to certificate resource will be provided. In case a CSR got rejected the order status will be changed to “invalid”. Just a look into ```examples/ca_handler/certifier_ca_handler.py``` which contains an example implementation. I also put some short description into [ca_handler.md](https://github.com/grindsa/acme2certifier/blob/devel/docs/ca_handler.md).

I will also upload an example ```acme_srv.db``` that you get a better understanding on the values especially in the certificate table.

Feel free to give it a try and let me know if you have further questions.

Happy testing
/G

BTW: if you are upgrading from an older version you need to run the ```db_upgrade.py``` to extend your certificate table by the ```poll_identifier``` field

**Comment by pfisterer** [comment]
@grindsa Great, thanks a million. I'll give it a try as soon as I have access to the SOAP server. I'm still waiting for a client certificate required for authentication...

**Comment by pfisterer** [comment]
Hello @grindsa, I was now able to actually run a custom ca_handler in Docker. To simplify development on Kubernetes, I would love to use an existing Docker image. Do you think, you could [setup an automated build](https://docs.docker.com/docker-hub/builds/) to create a docker images automatically?

p.s. for testing purposes, I've set this up for a fork of your repo at [https://hub.docker.com/r/farberg/acme2certifier](https://hub.docker.com/r/farberg/acme2certifier).

**Comment by grindsa** [comment]
This is indeed a good idea. We did some research and will provide prepared images for apache2/nginx for both wsgi and django adapters starting from 0.12  (so hopefully in a couple of days from now). A [repository containing images for 0.11.1](https://hub.docker.com/r/grindsa/acme2certifier) is already available.

**Comment by pfisterer** [comment]
Great, thanks a million. I got it working in Kubernetes with my own ca handler. I‘m currently waiting for feedback from the CA providing the SOAP API. I‘ll upload my code as soon as I have a prototype up and running.

**Comment by pfisterer** [comment]
@grindsa I've made some progress and have published my work here: https://github.com/pfisterer/acme2dfn. However, I cannot continue until [DFN PKI](https://www.pki.dfn.de/ueberblick-dfn-pki/) implements some changes.

**Comment by grindsa** [comment]
Thanks for sharing the repo. You could potentially unblock your tests by using [acme.sh](https://github.com/acmesh-official/acme.sh) instead of `certbot`  as `acme.sh` sets a the first fqdn you specify as CN. Another option would be to use `cert-manager` and configure your manifest accordingly.

**Comment by pfisterer** [comment]
Thanks for the ideas.  Can you point me to an example with `cert-manager` and according manifests? I guess this is what I would need...

**Comment by grindsa** [comment]
I updated the [cert-manager](https://github.com/grindsa/acme2certifier/blob/master/docs/cert-mgr.md) documentation with an example and tested with cert-manager 1.0.3 without problems.  I also noticed that the first SAN is being used as CN if `commonName` is not set.

**Comment by pfisterer** [comment]
@grindsa Thanks a million for your support. I have now successfully used the polling feature (cf. https://github.com/pfisterer/acme2dfn).
