### ISSUE TITLE
account registration fails for domains with "-" (i.e. test@example-domain.com)

### ISSUE THREAD

**Issue by flosch-dev** [grindsa/acme2certifier#35]
When trying to register email/account with domain including "-", registration fails.

Registration command:
`acme.sh --server http://acme-srv --register-account --accountemail "test@example-domain.com" --debug 2 --output-insecure`
`[Mon Jun 29 18:33:25 UTC 2020] code='400'`
`[Mon Jun 29 18:33:25 UTC 2020] original='{"status": 400, "message": "urn:ietf:params:acme:error:invalidContact", "detail": "The provided contact URI was invalid: mailto:test@example-domain.com"}'`
`[Mon Jun 29 18:33:25 UTC 2020] response='{"status": 400, "message":"urn:ietf:params:acme:error:invalidContact", "detail":"The provided contact URI was invalid: mailto:test@example-domain.com"}'`
`[Mon Jun 29 18:33:25 UTC 2020] Register account Error: {"status": 400, "message":"urn:ietf:params:acme:error:invalidContact", "detail":"The provided contact URI was invalid: mailto:test@example-domain.com"}`

acme2certifier output:
`cme-srv_1  | [Mon Jun 29 20:33:25.579465 2020] [wsgi:error] [pid 15:tid 139714361964288] [remote 192.168.0.4:39014] Signature.check() ended with: True:None`
`acme-srv_1  | [Mon Jun 29 20:33:25.579547 2020] [wsgi:error] [pid 15:tid 139714361964288] [remote 192.168.0.4:39014] Message.check() ended with:200`
`acme-srv_1  | [Mon Jun 29 20:33:25.579598 2020] [wsgi:error] [pid 15:tid 139714361964288] [remote 192.168.0.4:39014] Account._contact_check()`
`acme-srv_1  | [Mon Jun 29 20:33:25.579664 2020] [wsgi:error] [pid 15:tid 139714361964288] [remote 192.168.0.4:39014] validate_email()`
`acme-srv_1  | [Mon Jun 29 20:33:25.580070 2020] [wsgi:error] [pid 15:tid 139714361964288] [remote 192.168.0.4:39014] # validate: test@example-domain.com result: False`
`acme-srv_1  | [Mon Jun 29 20:33:25.580121 2020] [wsgi:error] [pid 15:tid 139714361964288] [remote 192.168.0.4:39014] Account._contact_check() ended with:400`
`acme-srv_1  | [Mon Jun 29 20:33:25.580186 2020] [wsgi:error] [pid 15:tid 139714361964288] [remote 192.168.0.4:39014] Message.prepare_response()`
`acme-srv_1  | [Mon Jun 29 20:33:25.580246 2020] [wsgi:error] [pid 15:tid 139714361964288] [remote 192.168.0.4:39014] Error.enrich_error()`
`acme-srv_1  | [Mon Jun 29 20:33:25.580317 2020] [wsgi:error] [pid 15:tid 139714361964288] [remote 192.168.0.4:39014] Error.acme_errormessage(urn:ietf:params:acme:error:invalidContact)`
`acme-srv_1  | [Mon Jun 29 20:33:25.580404 2020] [wsgi:error] [pid 15:tid 139714361964288] [remote 192.168.0.4:39014] Account.account_new() returns: {"code": 400, "header": {}, "data": {"status": 400, "message": "urn:ietf:params:acme:error:invalidContact", "detail": "The provided contact URI was invalid: mailto:test@example-domain.com"}}`
`acme-srv_1  | [Mon Jun 29 20:33:25.580522 2020] [wsgi:error] [pid 15:tid 139714361964288] [remote 192.168.0.4:39014] 192.168.0.4 /acme/newaccount {'code': 400, 'header': {}, 'data': {'status': 400, 'message': 'urn:ietf:params:acme:error:invalidContact', 'detail': 'The provided contact URI was invalid: mailto:test@example-domain.com'}}`

**Comment by grindsa** [comment]
fixed in 5f6f766bc

**Comment by flosch-dev** [comment]
I've tested and it works.
