### ISSUE TITLE
[xca_handler] error handling

### ISSUE THREAD

**Issue by flosch-dev** [grindsa/acme2certifier#38]
several errors result in Traceback (most recent call last):
- "issuing_ca_name" incorrect
- "passphrase" incorrect
- "ca_cert_chain_list" contains non-existing reference

**Comment by grindsa** [comment]
I pushed a couple of commits (461f5bb, 37f0110,   89e8638) to the devel branch which should improve the error handling of xca_ca_handler.py

**Comment by flosch-dev** [comment]
tested and works - thanks
