### ISSUE TITLE
[improvement request] DB clean-up

### ISSUE THREAD

**Issue by flosch-dev** [grindsa/acme2certifier#39]
acme_srv.db regardless of wsgi or django can grow over time and contain a lot of obsolet data.
Following suggestions to keep db more lean:

- in table "certificates" add field of cert expiration time -> this can be used to run periodically clean-up rules
- using "expires" in table "authorizaiton"  and clean-up authorizations:
`DELETE * from AUTHORIZATION WHERE expires < CURRENT_TIMESTAMP`
- using configuration (acme_srv.cfg) to define account expiration

**Comment by grindsa** [comment]
The [housekeeping](https://github.com/grindsa/acme2certifier/blob/devel/docs/housekeeping.md) contains a method to clear expired certificates from database. There is also [an example script](https://github.com/grindsa/acme2certifier/blob/devel/tools/report_generator.py) containing reporting and cleaning examples.

Feel free to play with it and let me know if it works.

**Comment by grindsa** [comment]
Implemented in [v0.11](https://github.com/grindsa/acme2certifier/releases/tag/0.11.1). Closing issue....
