### ISSUE TITLE
An invalid link in docs

### ISSUE THREAD

**Issue by DobroAlex** [grindsa/acme2certifier#40]
In https://github.com/grindsa/acme2certifier/blob/master/docs/ca_handler.md there is the sentence 
`The stub_handler.py contains a skeleton which can be used to create customized ca_handlers.` with the link to https://github.com/grindsa/acme2certifier/blob/master/docs/examples/ca_handler/skeleton_ca_handler.py which lead to 404

**Comment by grindsa** [comment]
Thanks for reporting. Fixed in f1bd5e2f.

/G.
