### ISSUE TITLE
missing status change when validation failed 

### ISSUE THREAD

**Issue by flosch-dev** [grindsa/acme2certifier#41]
I've tested acme2certifier with incorrect DNS host entry.
DNS server replied NXDOMAIN, but status is not changed to invalid.
![image](https://user-images.githubusercontent.com/47741987/87684825-fc40c300-c782-11ea-9580-3db04c712485.png)

Also client does not know state change and keeps trying to request.

**Comment by grindsa** [comment]
fix implemented in v0.11 and later releases. Closing issue
