### ISSUE TITLE
Setup instruction lead to the wrong file

### ISSUE THREAD

**Issue by DobroAlex** [grindsa/acme2certifier#45]
https://github.com/grindsa/acme2certifier/blob/master/docs/install_nginx_wsgi.md  is called "Installation as WSGI-script running on NGINX" but the article is about apache  and is a duplicate of https://github.com/grindsa/acme2certifier/blob/master/docs/install_apache2_wsgi.md

**Comment by DobroAlex** [comment]
I couldn't find a valid  candidate in the "/docs/" folder too

**Comment by grindsa** [comment]
Stupid copy and paste error already fixed in [devel branch](https://github.com/grindsa/acme2certifier/blob/devel/docs/install_nginx_wsgi.md). But thx for reporting.

**Comment by DobroAlex** [comment]
Thanks
