### ISSUE TITLE
Suggestion: remove data from acme/acme_srv.db.my

### ISSUE THREAD

**Issue by DobroAlex** [grindsa/acme2certifier#46]
I have opened the file called "acme/acme_srv.db" and it contains some data. I don't think it's of any importance but I would suggest making this  file empty leaving only structure but not the data
![image](https://user-images.githubusercontent.com/23741647/89918591-e64be400-dc02-11ea-9a3d-cb53f29cfa1c.png)

**Comment by grindsa** [comment]
thx for reporting. fixed in 631dda8
