### ISSUE TITLE
fqdn_resolve() does not resolve ipv6

### ISSUE THREAD

**Issue by deep-42-thought** [grindsa/acme2certifier#50]
fqdn_resolve() in acme/helper.py does not query AAAA records and thus does not find host names, that only resolve to ipv6 addresses. For whatever reason, this has not been an issue in the past (I cannot git-blame it on any commit), but I think, it should be fixed anyways :-)

**Comment by deep-42-thought** [comment]
On second thought, maybe this never worked, and my dns was just (wrongly) giving (valid) ipv4 addresses for all host names. (I have some hostnames set up to only resolve to ipv4, some to only resolve to ipv6)

**Comment by grindsa** [comment]
Included in 0.13.1.  BTW: `fqdn_resolve()` has been introduced to address the issue reported in #41.
