### ISSUE TITLE
order looping

### ISSUE THREAD

**Issue by delpeso** [grindsa/acme2certifier#52]
Hi,

I am using cert-manager to acme2certificer to microsoft ADCS.

When I deploy an application in kubernetes, cert-manager does ask for a certificate, everything is going perfectly, I get the certificate well.

In cert-manager, challenges and orders are validated, but at the end I have new order requests, and it loops indefinitely.

The order id changes with each new request. And I don't see any error in acme2certificer nor in cert-manager.

I am attaching the logs of cert-manager and acme2certifier.

Do you have any idea of the problem.

Thank you in advance.
best regards.
[acme2certifier-test2.log](https://github.com/grindsa/acme2certifier/files/5836720/acme2certifier-test2.log)
[certmanager-test2.log](https://github.com/grindsa/acme2certifier/files/5836723/certmanager-test2.log)

**Comment by grindsa** [comment]
Hi,

Indeed it looks weird. Line 523 from `certmanager-test2.log` indicates an encoding issue in the response of the cert-request but I am not familiar enough with cert-manager to conclude on this.  Let me try to replicate it in my lab. Which cert-manager version are you using?

I see that you are using http. Is there any chance to provide a new set of logs showing the problem as well as a pcap-trace showing the packets on the wire?

/G.

**Comment by delpeso** [comment]
HI, 
Thanks for your feedback.

I am using kubernetes v1.18.4 and cert-manager version 1.1.0 deployed with the charts helm.

I made a pcap capture on cert-manager and one on the acme2certifier server.

I attach you the logs
I renamed the pcap file to .txt because it did not work
thanks in advance

best regards.

[acme2certifier.txt](https://github.com/grindsa/acme2certifier/files/5842804/acme2certifier.txt)
[cert-manager.txt](https://github.com/grindsa/acme2certifier/files/5842805/cert-manager.txt)

[certmanager-test4.log](https://github.com/grindsa/acme2certifier/files/5842787/certmanager-test4.log)
[certmanager-test4.log](https://github.com/grindsa/acme2certifier/files/5842788/certmanager-test4.log)

**Comment by grindsa** [comment]
Hi,

I was able to replicate the behaviour you observed in my setup. I think the problem is that your certificates have a validity time of 30 days only meaning the default renewal window from cert-manager (90days) immediately kicks in and triggers a certificate renewal and causing the loop.

```
root@ub18-04:/tmp# openssl x509 -in delpeso.pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            31:00:00:11:41:48:db:ec:d4:44:10:98:cd:00:00:00:00:11:41
        Signature Algorithm: sha1WithRSAEncryption
        Issuer: DC = local, DC = racine-np, DC = ressources-np, CN = BureautiqueGroupe-np
        Validity
            Not Before: Jan 20 13:24:58 2021 GMT
            Not After : Feb 19 13:24:58 2021 GMT
````
I was able to fix this by setting the `renewBefore` parameter as described in [cert-manager documentation](https://docs.cert-manager.io/en/release-0.8/reference/certificates.html). Please give it a try and check if it works at your end as well.

/G.

**Comment by delpeso** [comment]
HI,

I apologize for not having answered you earlier, because on Friday I did not have time to test.

I modified the certificate template for a period of 90 days and everything works fine.

thank you so much,

best regards.
