### ISSUE TITLE
EAB registration - database trail

### ISSUE THREAD

**Issue by Flo451** [grindsa/acme2certifier#55]
Hi,

first thanks for the amazing work on this project. 

With the recent introduction of EAB support I was wondering if new account requests could also leave a trail in the database to see which EAB_key_id was used to register an account? 

In this way we can ensure we know exactly which ACME account is associated with a specific EAB account.

**Comment by grindsa** [comment]
I extended the "accounts" table with a field "eab_kid" which contains the kid used during account registration. Changes are in already included in [0.15](https://github.com/grindsa/acme2certifier/releases/tag/0.15). Feel free to give it a try and please let me know if this is enough for you.

**Comment by Flo451** [comment]
Thanks, this looks very good! I can now track which EAB account requested certificates.

Thanks you!
