### ISSUE TITLE
Docker compose timezone handling is Ubuntu specific

### ISSUE THREAD

**Issue by erinn** [grindsa/acme2certifier#56]
The handling of timezones in docker-compose is a bit britle as it it is very specific to being run off of an Ubuntu host platform. /etc/timezone doesn't exist in Fedora for instance. Using the TZ environment variable is more robust. PR incoming for this.

**Comment by grindsa** [comment]
Thx for the remark and the improvement. PR has been merged into devel and 0.15 maintenance branches
