### ISSUE TITLE
incorrect dns query / record type for DNS validation

### ISSUE THREAD

**Issue by flosch-dev** [grindsa/acme2certifier#59]
I'm running latest acme2certifier and noticed DNS validation doesn't work and prompt "orderNotReady"
![image](https://user-images.githubusercontent.com/47741987/117219428-8b4bc400-ae05-11eb-8c30-71c164ea88d7.png)

When checking the DNS queries send by acme2certifier host, I noticed record types are A or AAA.
however, acme2certifier should query TXT.
![image](https://user-images.githubusercontent.com/47741987/117219555-cd750580-ae05-11eb-9bbe-bc456285cbfc.png)

I tried using both, dns_server_list in config and system DNS server.

My system is running as docker container.

**Comment by grindsa** [comment]
Fixes are included in [0.15.1](https://github.com/grindsa/acme2certifier/releases/tag/0.15.1). From now on dns-challenge validation is part of [regular regression](https://github.com/grindsa/acme2certifier/blob/0.15.1/.github/workflows/dns-test.yml)

**Comment by flosch-dev** [comment]
I've tested with [0.15.2](https://github.com/grindsa/acme2certifier/releases/tag/0.15.2 ) and problem is fixed.
Thanks
