### ISSUE TITLE
enhancement: passphrase for xca key in environment variable

### ISSUE THREAD

**Issue by flosch-dev** [grindsa/acme2certifier#60]

**Comment by grindsa** [comment]
I created a [dev branch](https://github.com/grindsa/acme2certifier/tree/handler_env) containing an enhanced xca_handler. There is also a containerized version available which can be installed `docker pull grindsa/acme2certifier:handler_env`.

You need change your `acme_srv.cfg`, remove the `passphrase` parameter and specify the variable name via `passphrase_variable` parameter. 

So something like
```
[CAhandler]
...
passphrase_variable: XCA_PASSPHRASE
``` 

The container must be started with `-e XCA_PASSPHRASE=test1234` option

Feel free to give it a try and let me know if it works for you

**Comment by grindsa** [comment]
Changes made it finally into [0.16](https://github.com/grindsa/acme2certifier/releases/tag/0.16)

**Comment by flosch-dev** [comment]
thank you very much, works good in 0.16
