### ISSUE TITLE
2x key-usage field 

### ISSUE THREAD

**Issue by flosch-dev** [grindsa/acme2certifier#62]
I'm using version "handler_env" with xca handler as I wanted to test #60 and I noticed that issued certs having 2x key-usage set:

![acme2cert_issue](https://user-images.githubusercontent.com/47741987/119239440-4e900480-bb49-11eb-9164-fd4bf0f9c149.png)

Problem happens w/ and w/o xca template.

**Comment by flosch-dev** [comment]
this issue seems to be related to ca_handler for xca and I think the right order of attributes in signed cert might be:
1. attributes in xca_template
2. attributes from csr (if not defined in xca_template)
3. ca_handler defaults (missing/incorrect mandatory attributes in csr)

**Comment by grindsa** [comment]
I pushed a [new xca_ca_handler](https://raw.githubusercontent.com/grindsa/acme2certifier/devel/examples/ca_handler/xca_ca_handler.py) into the devel branch which should address the issue. Feel free to give it a try and let me know if it works for you.

**Comment by flosch-dev** [comment]
I have tested w/ and w/o xca template and both cases works now as expected.
Thanks
