### ISSUE TITLE
selectively proxy outgoing requests

### ISSUE THREAD

**Issue by deep-42-thought** [grindsa/acme2certifier#72]
Hi grindelsack,

it would be nice to have configurable (depending on the to-be-validated tld) proxies for outgoing connections.
My use case is an acme server which (also) validates onion addresses by passing this traffic through tor.

Do you think, that this is a useful feature, or should I rather look to implement this somehow else (set up dns resolution for .onion, add suitable routes and some iptables/socks-magic for tor)?

regards,
Erich

**Comment by grindsa** [comment]
Hi

this sounds interesting.  I am planning to finish the work on version 0.17 this week and this could be a candidate for 0.18.

Proxying of http/tls-alpn challenges verification should be pretty straight forward.   Proxing DNS challenge validation can get tricky but I need to investigate this a bid more in detail. Would http-proxy support be enough or do you need socks support as well?

BR
/G.

**Comment by deep-42-thought** [comment]
http proxy would not suffice (if you mean http(s) proxy vs. socks proxy), I'm afraid. However, I think, *my* usecase doesn't need dns challenges, because there's no dns beneath .onion second-level domains anyways, as far as I understand.

Regarding the proxy type: I played a little with the `proxies={}` attribute to `requests.get()` and this seems to work pretty straight forwardly: `requests.get(url, proxies={'https': 'socks5://' + proxy + ':' + port})` - if one imports `pysocks` and `socks` first. So the type itself seems to be a no-brainer (though, the switching logic will need some thinking).

**Comment by grindsa** [comment]
I pushed the first set of changes into [challenge_proxy](https://github.com/grindsa/acme2certifier/tree/challenge_proxy) branch.
Both socks5 and http(s) proxies work in my environment.

Installing  `pysocks` via pip was enough on my side; no need for an additional import.

Proxies can be configured per domain/hostname in acme_srv.cfg as shown below
```
[DEFAULT]
debug: True
proxy_server_list: {"bar.local$": "socks5://192.168.14.135:1080", "foo.local$": "socks5://192.168.14.136:1080"}
```
the mapping function between fqdn and entries in the list still needs to be improved. So please do not configure complex rules :-)

Feel free to give it a try and let me know if it works for you.

**Comment by deep-42-thought** [comment]
I finally got around to try the `challenge_proxy` branch (rebased onto master) - currently, I get
```
[2021-07-18T11:22:18+0200] [ALPM-SCRIPTLET] /var/lib/acme2certifier/tools/../acme_srv/helper.py:600: SyntaxWarning: "is not" with a literal. Did you mean "!="?
[2021-07-18T11:22:18+0200] [ALPM-SCRIPTLET]   if regex is not '*':
[2021-07-18T11:22:21+0200] [ALPM-SCRIPTLET] Traceback (most recent call last):
[2021-07-18T11:22:21+0200] [ALPM-SCRIPTLET]   File "/var/lib/acme2certifier/tools/db_update.py", line 8, in <module>
[2021-07-18T11:22:21+0200] [ALPM-SCRIPTLET]     from acme_srv.db_handler import DBstore
[2021-07-18T11:22:21+0200] [ALPM-SCRIPTLET] ModuleNotFoundError: No module named 'acme_srv.db_handler'
```
upon installation - will change the `is not` to an `!=` and see, if everything works out :)

**Comment by deep-42-thought** [comment]
hmm, the proxy selection logic works, and the challenge is successfully answered, but currently, I'm unable to get *any* certificate rolled out (neither proxy-matching ones nor non-proxy-matching ones) ...
looks, like I broke something when the `acme` dir was moved to `acme_srv` or so.

**Comment by grindsa** [comment]
I just fixed the `if regex is not '*':` error.

The error resulting from `db_update.py` indicates that the database handler is missing in the `acme_srv` directory. You can fix this by copying the correct handler from `examples/db_handler` and rename it to `db_handler.py`

I would need a debug log to look into the enrollment issue. Can you enable debug mode, try to enroll a certificate and attach the logfile?

**Comment by deep-42-thought** [comment]
I found the cause, myself: the import was already fixed (as mentioned) by your suggested command - the other problem was, that I had some paths (to the signing key and intermediate cert) hard coded in acme_srv.cfg, which I missed to update :)

**Comment by deep-42-thought** [comment]
looks, like onion signing (through my proxy) works as expected - thank you!

**Comment by grindsa** [comment]
The feature made it into [v0.18](https://github.com/grindsa/acme2certifier/releases/tag/0.18). Thus, I am closing this issue.
