### ISSUE TITLE
no CN is being set

### ISSUE THREAD

**Issue by deep-42-thought** [grindsa/acme2certifier#73]
It appears, that certificates are missing a common name under certain conditions. I can not really spot a pattern, but most of my certificates miss one. The acme client, I used, was certbot, the validation method http challenge and the backend openssl. I guess, I can create and share some logs, if it's needed.

**Comment by grindsa** [comment]
This is rather a certbot than an acme2certifier issue as certbot does not set a subject CN by default. See [this issue](https://github.com/certbot/certbot/issues/7620) for further information. A workaround would be to extend the ca-handler and replicate the LE behaviour meaning we could set the first SAN from the CSR as CN. Would this be an acceptable way forward?

**Comment by deep-42-thought** [comment]
ah, I see. In that case, I would say, it is fine for me: You can close the bug. You do not need to code around certbot bugs :)

**Comment by jonaharagon** [comment]
Do all ACME clients seem to do this, or Certbot specifically? I would personally vote for replicating LE behavior in this case either way. I didn't realize CN matching was depreciated, but even so most keychain software and browsers still use the CN as a label for the certificate, so having one set would be helpful for viewing/organizing certificates.

**Comment by grindsa** [comment]
Such behaviour seems to be related to certbot only. Other acme clients I use for testing (acme.sh, winacme, lego, cert-manager) do use the first SAN from CSR as CN. I had a look into the code of the openssl_ca_handler; the change seems to be straight forward;, we can even make it configurable in acme_srv.cfg in the `CAhandler` section.

**Comment by grindsa** [comment]
I updated the [openssl_ca_handler.py](https://github.com/grindsa/acme2certifier/blob/cn_enforce/examples/ca_handler/openssl_ca_handler.py) to support using the first SAN as CN.  The feature must be activated by adding `cn_enforce: True` parameter into the `[CAhandler]` section of acme_srv.cfg. Feel free to give it a try (you just need to replace the existing handler file with the above one) and let me know if it works for you.

**Comment by deep-42-thought** [comment]
yes, works - thank you!

**Comment by grindsa** [comment]
The feature made it into [v0.18](https://github.com/grindsa/acme2certifier/releases/tag/0.18). Thus, I am closing this issue.
