### ISSUE TITLE
kind help in configuring acme2certifier to use MS Cert Enrollment Service

### ISSUE THREAD

**Issue by lwiechec** [grindsa/acme2certifier#74]
Hello, I am sure that I am doing something wrong with the configuration.

I am trying to run from the container (the one from Docker Hub) and try to configure it to 'talk' to our local CA server (which is Microsoft Certificate Enrollment Services.

The 'connection' test passes for NTLM when I test my CA's admin user, so I assume that I can 'talk' to the CA.

Following the documentation, I replace `ca_handler.py` with `examples/mscertsrv_ca_handler.py' and I update the `acme_srv.cfg` file with the details under '[CAhandler]` section.

When I test using `acme.sh`, it fails but I think that it is not even connecting to MS Cert Enrollment Services, because when I use `tshark` I don't see any outgoing TCP connections to this server...

Any help would be appreciated - it would be great the be able to generate the SSL certs automatically and not by hand...

**Comment by grindsa** [comment]
Hi,
Indeed, it seems to be a configuration issue. I do not suggest to copy the handler file anymore (need to update the documentation about this)  but rather to use the `handler_file` parameter in the `[CAhandler]` section of `acme_srv.cfg`. So something like below

```cfg
[CAhandler]
handler_file: examples/ca_handler/mscertsrv_ca_handler.py
host: <your data>
<and all your other paramteres>
````
Main reason this will ensure that you will always use the newest handler version. Restart your container and re-run your test.

If this does not work please enable the debug-mode in `acme_srv.cfg` 
```cfg
[DEFAULT]
debug: True
```
restart your container, re-run your test and share a the output of `docker logs <your container>` for further analysis.

Thx and br
/GrindSa

**Comment by lwiechec** [comment]
hi, thanks for such speedy help!

I have changed the config file accordingly; now I have:

```
[CAhandler]
# CA specific options
handler_file: /var/www/acme2certifier/examples/ca_handler/mscertsrv_ca_handler.py
host: 1.2.3.4 # edited
user: myuser
password: mypasswd
auth_method: ntlm
template: WebServer
ca_bundle: /var/www/acme2certifier/volume/ais-dc1-ca.p7b
```
and I *think* it took effect (the log is longer) but I still am getting a strange error and `tshark` is still not showing any outgoing traffic. 

I turned on debug and put the log file [here](https://gist.github.com/lwiechec/80857ba17448d5fcb716978fc3871913).

**Comment by grindsa** [comment]
According to the log the challenge validation via http failed as it seems that name resolution for `grafana.csd-monitor.ais.foo.com` failed.

```
Challenge._validate_http_challenge(LFS7lRbJdNsP:grafana.csd-monitor.ais.foo.com:2IDKVPcJBFkPfGseFxVM8TZQkoOPJzCx)
fqdn_resolve() ended with: None/True
Challenge._validate_http_challenge() ended with: False/True
```

To test the handler you can disable challenge validation in `acme_srv.cfg` by setting the below option, however I would not recommend this in a production environment.

```
[Challenge]
# when true disable challenge validation. Challenge will be set to 'valid' without further checking
# THIS IS A SEVERE SECURTIY ISSUE! Please do only for testing/debugging purposes
challenge_validation_disable: True
```
So its maybe better add a DNS record pointing to the ip-address of `grafana.csd-monitor.ais.foo.com`

**Comment by lwiechec** [comment]
@grindsa thanks again for a very thorough help - I really appreciate it!

Indeed, the DNS settings on the machine running `acme2certifier` was incorrect; I fixed that. Basic stuff but I forgot about it...

I think I am _almost_ there. If I might ask for probably for final piece of advice: I am trying to employ [acme-companion](https://github.com/nginx-proxy/acme-companion) to use `acme2certifier` and I can see that the former is contacting the latter. However, when `acme-companion` is trying to request the certificate via `acme2certifier`, I can see that the former replies with error that the requesting account does not exist (see [the log](https://gist.github.com/lwiechec/4526f93b1b7a4fa7b8d3424847c35633)).

I will ask at the `acme-companion` project for some help.

**Comment by grindsa** [comment]
Thx for the explanation. I see that acme-companion is using `acme.sh` so it should work in principle as i am using this tool for regression testing. 

I also checked the logs. I seems that you are using an account which is not known to acme2certifier. Thus the request gets rejected. Is it really the complete log? Could it be that this is a leftover from former testing? I suggest to clean the `acme` volume you are mounting as `/etc/acme-sh` inside the acme-companion container and try again. Then acme.sh should trigger a new account creation on acme2certifier.

**Comment by lwiechec** [comment]
hi again, thanks for the help - indeed, the old cache data was to blame.

I am still having trouble getting the certificates - in the end the error reported is 'internal server error', but in the amce2certifier I can see the following:

```
...
Certificate._config_load()
Certificate._ca_handler_get(/var/www/acme2certifier/examples/ca_handler/mscertsrv_ca_handler.py)
Certificate._ca_handler_get() ended with: .var.www.acme2certifier.examples.ca_handler.mscertsrv_ca_handler
Certificate._config_load(): loading CAhandler configured in cfg failed with err: the 'package' argument is required to perform a relative import for '.var.www.acme2certifier.examples.ca_handler.mscertsrv_ca_handler'
ca_handler: <module 'acme_srv.ca_handler' from '/var/www/acme2certifier/./acme_srv/ca_handler.py'>
Certificate._config_load() ended.
...
```

and I don't see 'package' in '[CAhandler]` section in `acme_srv.cfg`?...

**Comment by grindsa** [comment]
Can you please share your acme_srv.cfg and a debug log?

Thx and br
/G

**Comment by lwiechec** [comment]
hello again,

I have put them both in [here](https://gist.github.com/lwiechec/6f365119a491b793a17bbfcfd56fe19e). Thanks for help!

**Comment by grindsa** [comment]
Thx for sharing. I think the issue is on my side as I gave you a an absolute path for the `handler_file` variable instead of a relative one.

Please change the `handler_file` variable as below and re-run your test.
```
[CAhandler]
# CA specific options
handler_file: examples/ca_handler/mscertsrv_ca_handler.py 
````

Seems I introduced this bug and did not catch it during regression.  Will fix it in a later release as the above workaround should work for you.

**Comment by lwiechec** [comment]
hi again, thanks for help... I might have used the full path instead of relative myself; apologies. 

After changing to relative - all works.

Thanks for all the help!
