### ISSUE TITLE
Suggestion for new CA handler: Windows Client Certificate Enrollment Protocol (MS-WCCE) via RPC/DCOM

### ISSUE THREAD

**Issue by mlegner** [grindsa/acme2certifier#79]
Currently, `acme2certifier` supports the [Microsoft Certification Authority Web Enrollment Service](https://github.com/grindsa/acme2certifier/blob/master/docs/mscertsrv.md) via HTTPS. It would be great to also support the [Windows Client Certificate Enrollment Protocol](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-wcce) over DCOM.

The implementation could take the code from https://github.com/ly4k/Certipy as an inspiration, which itself uses [impacket](https://pypi.org/project/impacket/).

I would be happy to create a PR for this handler.

**Comment by grindsa** [comment]
This is on my list since quite a while but I did not find the time to look into this. So feel free to create a PR.

**Comment by mlegner** [comment]
@grindsa Should I create a new PR based on branch `pr_80`?

**Comment by grindsa** [comment]
Yes. Please do so..
