### ISSUE TITLE
duplicate or incomplete Wiki pages for containerize installation

### ISSUE THREAD

**Issue by lebeno** [grindsa/acme2certifier#82]
Wiki page "Containerized installation" has text "Containerized installation using apache2/nginx as webserver and wsgi or django" and a link "acme2certifer in Docker". The link goes to URL `https://github.com/grindsa/acme2certifier/examples/Docker` and results in a 404 error. Looks like the correct URL should be 
`https://github.com/grindsa/acme2certifier/tree/master/examples/Docker`

Regarding these wiki pages:

- Containerized installation using apache2 as webserver and wsgi or django
- Containerized installation using apache2 or nginx as webserver and wsgi or django

Both pages are very similar and it looks like the latter is the same as https://github.com/grindsa/acme2certifier/tree/master/examples/Docker. Would you consider deleting both pages because the first looks a bit outdated and the latter has the same info as the link on page "Containerized installation"?

**Comment by grindsa** [comment]
Thank you for the feedback. I know that documentation is one of my weak points. I already fixed the links in the wiki.  I will extend the documentation for the containerized images in the upcoming days. If you think that something else is missing besides the reference to the data directory let me know.

**Comment by grindsa** [comment]
I pushed additional explanations with 9c8ea9c9dc1c61468cf1e54748343fe9f43ca3e8 to the [README](https://github.com/grindsa/acme2certifier/blob/9c8ea9c9dc1c61468cf1e54748343fe9f43ca3e8/examples/Docker/README.md). Feel free to have a look and to share feedback.
