### ISSUE TITLE
Non-compliant content-type in error responses

### ISSUE THREAD

**Issue by RicMin** [grindsa/acme2certifier#85]
Hi, thanks for the good work. 
I would just like to report that the content-type of the failing responses should be changed as follows:

ContentType: application/problem+json

as indicated in https://datatracker.ietf.org/doc/html/rfc8555  and https://datatracker.ietf.org/doc/html/rfc7807

**Comment by grindsa** [comment]
Thx for filing the report. How did you recognize the issue? Any advice how to replicate the problem?

**Comment by grindsa** [comment]
I pushed some changes into [devel](https://github.com/grindsa/acme2certifier/tree/devel) branch. Will leave the issue open till the end up in master

**Comment by grindsa** [comment]
Fixed in v0.21
