### ISSUE TITLE
`docs/cmp.md` appears outdated

### ISSUE THREAD

**Issue by DDvO** [grindsa/acme2certifier#86]
Very nice to see that you support CMP, using the cmpossl client.
Yet please note that https://github.com/mpeylo/cmpossl/ has become obsolete due to the inclusion of CMP into OpenSSL 3.0.
A further, partly even more recent alternative is the generic CMP client: https://github.com/siemens/gencmpclient
which offers a more convenient API and provides basically the same CLI options.

**Comment by grindsa** [comment]
Migrating to the generic CMP client used in Openssl 3.0 or a pyopenssl version supporting CMPv2 is clearly a target for one of  the next releases.  But I prefer to wait till Ubuntu 22.04 is out as this will avoid dependency hell inside the container images. So stay tuned I promise it will come soon...

**Comment by grindsa** [comment]
addressed in v0.21...
