### ISSUE TITLE
Revoke certificate from acme2certifier not from client

### ISSUE THREAD

**Issue by flphrrr** [grindsa/acme2certifier#91]
Understanding the possibility that one System with Certificate provisioned via acme2certifier can be compromised, and consequently no possibility to start the revocation process from `acme_client` side, there is any way to start revocation process for an specific certificate from `acme2certifier_server` side, without involving `acme_client`?

**Comment by grindsa** [comment]
fix got included in v0.27. Thus, I am closing this issue...
