### ISSUE TITLE
health check

### ISSUE THREAD

**Issue by rismoney** [grindsa/acme2certifier#94]
is there a container url http to safely healthcheck?

**Comment by grindsa** [comment]
You could check the http[s]://<server_name or ip>/directory resource to verify that the container is up but this URL wont check the database-connection. If such check is needed let me know; we can easily add a database check...

**Comment by rismoney** [comment]
actually I think I am good.  I had a misconfigured resource on reverse proxy that was conflicting.  A db check might be good, but I don't have a concern with that, so you can close if you wish.

**Comment by grindsa** [comment]
Implementation is done (1082a240f2fb) and works fine. Some tests are still missing. I will leave this issue open till the changes will make it into master branch...

**Comment by grindsa** [comment]
Change made it into v.23. Closing the issue...
