### ISSUE TITLE
database error in Order._add() order: (1406, "Data too long for column 'identifiers' at row 1")

### ISSUE THREAD

**Issue by Flo451** [grindsa/acme2certifier#95]
Hello,

db column `identifiers varchar (1048)`  in table `acme_order` seems a bit small considering that any DNS alt name will consume ~50 chars or so. 
I think the db column should be somewhat aligned with theoretical limits of alt names. Running into this limit is now easily possible even with just 20 alt names but public CAs seem to support up to 2000 alt names, see the discussion in: https://discuss.httparchive.org/t/san-certificates-how-many-alt-names-are-too-many/1867

Would it make sense to raise the limits here?

**Comment by grindsa** [comment]
hi, thank you for pointing this out. It makes perfect sense to increase this limit. Will work on it the upcoming days.

BR Joern

**Comment by Flo451** [comment]
Thanks! The engine is MySQL. 

'ENGINE': 'django.db.backends.mysql',

**Comment by grindsa** [comment]
Fix finally made it into v.23. Closing the issue...
