### ISSUE TITLE
Certbot is not populating the CN field in the CSR

### ISSUE THREAD

**Issue by tomasfrommi** [grindsa/acme2certifier#98]
Our Microsoft PKI server issuing certificates fine but without Subject/Common name, all issued certificates have only Subject Alternative Name, no CN.
Any idea how to solve this issue without using other acme-clients like acme.sh or lego?

**Comment by grindsa** [comment]
I unfortunately do not have a good answer. This is something to be done by the CA and I do not know the MSCA good enough. Is there any way to enforce a CN via a CA template?
