### ISSUE TITLE
Authorization.value max_length too short for SAN entries.

### ISSUE THREAD

**Issue by FlorensDouwes** [grindsa/acme2certifier#99]
Related to #95, but the value field of the Authorization model is limited to 64 chars. I'm hitting an issue where my dns alternative name is more than 64 characters, and the following is raised: `acme2certifier database error in Order._add() authz: (1406, "Data too long for column 'value' at row 1")`

This is for the django backend.

Can we raise this limit? Also, as in #95, the max length on Order.identifiers is also not raised yet, is that a good idea too?

**Comment by grindsa** [comment]
Can you please specify the acme-client and the handler you are using? I would like to replicate this locally...

Thx
